package com.mycompany.farmaciasaludproyecto.view.menu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author cesar
 */
public class FRM_MENU_EMPLEADO extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MENU_EMPLEADO
     */
    public static JDesktopPane jDesktopPane_menu;

    public FRM_MENU_EMPLEADO() {
        initComponents();
        this.setSize(new Dimension(1400, 800));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de ventas MegaMarket");

        jDesktopPane_menu = new JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                // Cargar la imagen desde resources
                ImageIcon icon = new ImageIcon(getClass().getResource("/almaFarmacia.jpeg"));
                Image img = icon.getImage();

                // Dibujar la imagen si se cargó correctamente
                if (img != null) {
                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                } else {
                    System.out.println("Error: Imagen no encontrada en resources");
                }
            }
        };

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 100));
        this.add(jDesktopPane_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        gestionarUsuarios = new javax.swing.JMenuItem();
        menu_proveedor = new javax.swing.JMenu();
        MENU_GestionarProveedores = new javax.swing.JMenuItem();
        menu_medicamento = new javax.swing.JMenu();
        MENU_GestionarMedicamento = new javax.swing.JMenuItem();
        nuevo_tipoMedicamento = new javax.swing.JMenuItem();
        menu_cliente = new javax.swing.JMenu();
        MENU_nuevoCliente = new javax.swing.JMenuItem();
        MENU_GestionarClientes = new javax.swing.JMenuItem();
        menu_facturar = new javax.swing.JMenu();
        MENU_nuevaVenta = new javax.swing.JMenuItem();
        MENU_GestionarVentas = new javax.swing.JMenuItem();
        menu_descuento = new javax.swing.JMenu();
        MENU_NuevoDescuento = new javax.swing.JMenuItem();
        menu_devolucion = new javax.swing.JMenu();
        MENU_CrearDevolucion = new javax.swing.JMenuItem();
        MENU_historialDevoluciones = new javax.swing.JMenuItem();
        menu_cerrarSesion = new javax.swing.JMenu();
        MENU_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        menu_usuario.setForeground(new java.awt.Color(0, 0, 0));
        menu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero.png"))); // NOI18N
        menu_usuario.setText("Vendedor");
        menu_usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_usuario.setPreferredSize(new java.awt.Dimension(150, 50));

        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equipo.png"))); // NOI18N
        gestionarUsuarios.setText("Lista de vendedores");
        gestionarUsuarios.setPreferredSize(new java.awt.Dimension(250, 30));
        gestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarUsuariosActionPerformed(evt);
            }
        });
        menu_usuario.add(gestionarUsuarios);

        jMenuBar1.add(menu_usuario);

        menu_proveedor.setForeground(new java.awt.Color(0, 0, 0));
        menu_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensajero.png"))); // NOI18N
        menu_proveedor.setText("Proveedor");
        menu_proveedor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_proveedor.setPreferredSize(new java.awt.Dimension(160, 50));

        MENU_GestionarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proveedor.png"))); // NOI18N
        MENU_GestionarProveedores.setText("Lista de Proveedores");
        MENU_GestionarProveedores.setPreferredSize(new java.awt.Dimension(255, 45));
        MENU_GestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarProveedoresActionPerformed(evt);
            }
        });
        menu_proveedor.add(MENU_GestionarProveedores);

        jMenuBar1.add(menu_proveedor);

        menu_medicamento.setForeground(new java.awt.Color(0, 0, 0));
        menu_medicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamento (1).png"))); // NOI18N
        menu_medicamento.setText("Medicamento");
        menu_medicamento.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_medicamento.setPreferredSize(new java.awt.Dimension(160, 50));

        MENU_GestionarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tipo-de-sangre.png"))); // NOI18N
        MENU_GestionarMedicamento.setText("Lista de Medicamentos");
        MENU_GestionarMedicamento.setPreferredSize(new java.awt.Dimension(255, 30));
        MENU_GestionarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarMedicamentoActionPerformed(evt);
            }
        });
        menu_medicamento.add(MENU_GestionarMedicamento);

        nuevo_tipoMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico.png"))); // NOI18N
        nuevo_tipoMedicamento.setText("Tipos de medicamento");
        nuevo_tipoMedicamento.setPreferredSize(new java.awt.Dimension(255, 30));
        nuevo_tipoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_tipoMedicamentoActionPerformed(evt);
            }
        });
        menu_medicamento.add(nuevo_tipoMedicamento);

        jMenuBar1.add(menu_medicamento);

        menu_cliente.setForeground(new java.awt.Color(0, 0, 0));
        menu_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiencia.png"))); // NOI18N
        menu_cliente.setText("Cliente");
        menu_cliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_cliente.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente-satisfecho (1).png"))); // NOI18N
        MENU_nuevoCliente.setText("Nuevo Cliente");
        MENU_nuevoCliente.setPreferredSize(new java.awt.Dimension(235, 50));
        MENU_nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_nuevoClienteActionPerformed(evt);
            }
        });
        menu_cliente.add(MENU_nuevoCliente);

        MENU_GestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/la-satisfaccion-del-cliente.png"))); // NOI18N
        MENU_GestionarClientes.setText("Gestionar Clientes");
        MENU_GestionarClientes.setPreferredSize(new java.awt.Dimension(235, 50));
        MENU_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarClientesActionPerformed(evt);
            }
        });
        menu_cliente.add(MENU_GestionarClientes);

        jMenuBar1.add(menu_cliente);

        menu_facturar.setForeground(new java.awt.Color(0, 0, 0));
        menu_facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas.png"))); // NOI18N
        menu_facturar.setText("Venta");
        menu_facturar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_facturar.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas (1).png"))); // NOI18N
        MENU_nuevaVenta.setText("Nueva Venta");
        MENU_nuevaVenta.setPreferredSize(new java.awt.Dimension(225, 50));
        MENU_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_nuevaVentaActionPerformed(evt);
            }
        });
        menu_facturar.add(MENU_nuevaVenta);

        MENU_GestionarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto-de-venta.png"))); // NOI18N
        MENU_GestionarVentas.setText("Gestionar Ventas");
        MENU_GestionarVentas.setPreferredSize(new java.awt.Dimension(225, 50));
        MENU_GestionarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarVentasActionPerformed(evt);
            }
        });
        menu_facturar.add(MENU_GestionarVentas);

        jMenuBar1.add(menu_facturar);

        menu_descuento.setForeground(new java.awt.Color(0, 0, 0));
        menu_descuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descuento-3d.png"))); // NOI18N
        menu_descuento.setText("Descuento");
        menu_descuento.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_descuento.setPreferredSize(new java.awt.Dimension(170, 50));

        MENU_NuevoDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boleto.png"))); // NOI18N
        MENU_NuevoDescuento.setText("Lista de descuentos");
        MENU_NuevoDescuento.setPreferredSize(new java.awt.Dimension(270, 50));
        MENU_NuevoDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_NuevoDescuentoActionPerformed(evt);
            }
        });
        menu_descuento.add(MENU_NuevoDescuento);

        jMenuBar1.add(menu_descuento);

        menu_devolucion.setForeground(new java.awt.Color(0, 0, 0));
        menu_devolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queja.png"))); // NOI18N
        menu_devolucion.setText("Devolucion");
        menu_devolucion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_devolucion.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_CrearDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devolucion-de-dinero.png"))); // NOI18N
        MENU_CrearDevolucion.setText("Crear devolucion");
        MENU_CrearDevolucion.setPreferredSize(new java.awt.Dimension(250, 50));
        MENU_CrearDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_CrearDevolucionActionPerformed(evt);
            }
        });
        menu_devolucion.add(MENU_CrearDevolucion);

        MENU_historialDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/historial-de-transacciones.png"))); // NOI18N
        MENU_historialDevoluciones.setText("Historial");
        MENU_historialDevoluciones.setPreferredSize(new java.awt.Dimension(250, 50));
        MENU_historialDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_historialDevolucionesActionPerformed(evt);
            }
        });
        menu_devolucion.add(MENU_historialDevoluciones);

        jMenuBar1.add(menu_devolucion);

        menu_cerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        menu_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        menu_cerrarSesion.setText("Cerrar Sesion");
        menu_cerrarSesion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        MENU_cerrarSesion.setText("Cerrar Sesion");
        MENU_cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_cerrarSesionActionPerformed(evt);
            }
        });
        menu_cerrarSesion.add(MENU_cerrarSesion);

        jMenuBar1.add(menu_cerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_nuevoClienteActionPerformed
        // TODO add your handling code here:
        InterClienteSolucion cliente = new InterClienteSolucion();
        jDesktopPane_menu.add(cliente);
        cliente.setVisible(true);


    }//GEN-LAST:event_MENU_nuevoClienteActionPerformed

    private void MENU_CrearDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_CrearDevolucionActionPerformed
        // TODO add your handling code here:
        InternalCrearDevolucion devolucion = new InternalCrearDevolucion();
        jDesktopPane_menu.add(devolucion);
        devolucion.setVisible(true);

    }//GEN-LAST:event_MENU_CrearDevolucionActionPerformed

    private void MENU_historialDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_historialDevolucionesActionPerformed

        InterHistorialDevolucion historialDevolucion = new InterHistorialDevolucion();
        jDesktopPane_menu.add(historialDevolucion);
        historialDevolucion.setVisible(true);
    }//GEN-LAST:event_MENU_historialDevolucionesActionPerformed

    private void MENU_GestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarProveedoresActionPerformed

        InterListaProveedor gestionarProveedores = new InterListaProveedor();
        jDesktopPane_menu.add(gestionarProveedores);
        gestionarProveedores.setVisible(true);

    }//GEN-LAST:event_MENU_GestionarProveedoresActionPerformed

    private void gestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarUsuariosActionPerformed

        InterListaVendedor listaVendedor = new InterListaVendedor();
        jDesktopPane_menu.add(listaVendedor);
        listaVendedor.setVisible(true);

    }//GEN-LAST:event_gestionarUsuariosActionPerformed

    private void MENU_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarClientesActionPerformed
        // TODO add your handling code here:
        InterGestionarCliente clientes = new InterGestionarCliente();
        jDesktopPane_menu.add(clientes);
        clientes.setVisible(true);

    }//GEN-LAST:event_MENU_GestionarClientesActionPerformed

    private void MENU_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_nuevaVentaActionPerformed
        // TODO add your handling code here:
        InterRegistrarVenta venta = new InterRegistrarVenta();
        jDesktopPane_menu.add(venta);
        venta.setVisible(true);
    }//GEN-LAST:event_MENU_nuevaVentaActionPerformed

    private void MENU_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_cerrarSesionActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_MENU_cerrarSesionActionPerformed

    private void MENU_GestionarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarVentasActionPerformed

        InterGestionarVentas ventasGestion = new InterGestionarVentas();
        jDesktopPane_menu.add(ventasGestion);
        ventasGestion.setVisible(true);

    }//GEN-LAST:event_MENU_GestionarVentasActionPerformed

    private void MENU_NuevoDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_NuevoDescuentoActionPerformed

        InterListaDescuentos descuento = new InterListaDescuentos();
        jDesktopPane_menu.add(descuento);
        descuento.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_NuevoDescuentoActionPerformed

    private void MENU_GestionarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarMedicamentoActionPerformed
        // TODO add your handling code here:
        InterListaMedicamentos gestionarMedicamentos;
        try {
            gestionarMedicamentos = new InterListaMedicamentos();
            jDesktopPane_menu.add(gestionarMedicamentos);
            gestionarMedicamentos.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FRM_MENU_EMPLEADO.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_MENU_GestionarMedicamentoActionPerformed

    private void nuevo_tipoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_tipoMedicamentoActionPerformed
        // TODO add your handling code here:
        InterListaTipoMedicamentos tipoMedicamento = new InterListaTipoMedicamentos();
        jDesktopPane_menu.add(tipoMedicamento);
        tipoMedicamento.setVisible(true);

    }//GEN-LAST:event_nuevo_tipoMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU_EMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU_EMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU_EMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU_EMPLEADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MENU_EMPLEADO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MENU_CrearDevolucion;
    private javax.swing.JMenuItem MENU_GestionarClientes;
    private javax.swing.JMenuItem MENU_GestionarMedicamento;
    private javax.swing.JMenuItem MENU_GestionarProveedores;
    private javax.swing.JMenuItem MENU_GestionarVentas;
    private javax.swing.JMenuItem MENU_NuevoDescuento;
    private javax.swing.JMenuItem MENU_cerrarSesion;
    private javax.swing.JMenuItem MENU_historialDevoluciones;
    private javax.swing.JMenuItem MENU_nuevaVenta;
    private javax.swing.JMenuItem MENU_nuevoCliente;
    private javax.swing.JMenuItem gestionarUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_cerrarSesion;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenu menu_descuento;
    private javax.swing.JMenu menu_devolucion;
    private javax.swing.JMenu menu_facturar;
    private javax.swing.JMenu menu_medicamento;
    private javax.swing.JMenu menu_proveedor;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenuItem nuevo_tipoMedicamento;
    // End of variables declaration//GEN-END:variables
}
