package com.mycompany.farmaciasaludproyecto.view.menu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author cesar
 */
public class FRM_MENU extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MENU
     */
    public static JDesktopPane jDesktopPane_menu;

    public FRM_MENU() {
        initComponents();
        this.setSize(new Dimension(1400, 800));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de ventas MegaMarket");

        jDesktopPane_menu = new JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                // Cargar la imagen desde resources
                ImageIcon icon = new ImageIcon(getClass().getResource("/almaFarmacia.jpeg"));
                Image img = icon.getImage();

                // Dibujar la imagen si se cargó correctamente
                if (img != null) {
                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                } else {
                    System.out.println("Error: Imagen no encontrada en resources");
                }
            }
        };

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 100));
        this.add(jDesktopPane_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        menu_nuevoUsuario = new javax.swing.JMenuItem();
        gestionarUsuarios = new javax.swing.JMenuItem();
        menu_producto = new javax.swing.JMenu();
        nuevo_producto = new javax.swing.JMenuItem();
        MENU_GestionarProducto = new javax.swing.JMenuItem();
        menu_cliente = new javax.swing.JMenu();
        MENU_nuevoCliente = new javax.swing.JMenuItem();
        MENU_GestionarClientes = new javax.swing.JMenuItem();
        menu_facturar = new javax.swing.JMenu();
        MENU_nuevaVenta = new javax.swing.JMenuItem();
        MENU_GestionarVentas = new javax.swing.JMenuItem();
        menu_categoria = new javax.swing.JMenu();
        MENU_NuevoCategoria = new javax.swing.JMenuItem();
        MENU_gestionarCategoria = new javax.swing.JMenuItem();
        menu_categoria1 = new javax.swing.JMenu();
        MENU_NuevoCategoria1 = new javax.swing.JMenuItem();
        MENU_gestionarCategoria1 = new javax.swing.JMenuItem();
        menu_reportes = new javax.swing.JMenu();
        MENU_ReporteClientes = new javax.swing.JMenuItem();
        Menu_reporteCategoria = new javax.swing.JMenuItem();
        MENU_ReporteProductos = new javax.swing.JMenuItem();
        MENU_ReporteVentas = new javax.swing.JMenuItem();
        menu_cerrarSesion = new javax.swing.JMenu();
        MENU_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        menu_usuario.setForeground(new java.awt.Color(0, 0, 0));
        menu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero.png"))); // NOI18N
        menu_usuario.setText("Vendedor");
        menu_usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_usuario.setPreferredSize(new java.awt.Dimension(150, 50));

        menu_nuevoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        menu_nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero (1).png"))); // NOI18N
        menu_nuevoUsuario.setText("Nuevo Vendedor");
        menu_nuevoUsuario.setPreferredSize(new java.awt.Dimension(250, 30));
        menu_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_nuevoUsuarioActionPerformed(evt);
            }
        });
        menu_usuario.add(menu_nuevoUsuario);

        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equipo.png"))); // NOI18N
        gestionarUsuarios.setText("Gestionar Vendedores");
        gestionarUsuarios.setPreferredSize(new java.awt.Dimension(250, 30));
        gestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarUsuariosActionPerformed(evt);
            }
        });
        menu_usuario.add(gestionarUsuarios);

        jMenuBar1.add(menu_usuario);

        menu_producto.setForeground(new java.awt.Color(0, 0, 0));
        menu_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamento (1).png"))); // NOI18N
        menu_producto.setText("Medicamento");
        menu_producto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_producto.setPreferredSize(new java.awt.Dimension(160, 50));

        nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas.png"))); // NOI18N
        nuevo_producto.setText("Nuevo Medicamento");
        nuevo_producto.setPreferredSize(new java.awt.Dimension(255, 30));
        nuevo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_productoActionPerformed(evt);
            }
        });
        menu_producto.add(nuevo_producto);

        MENU_GestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actual.png"))); // NOI18N
        MENU_GestionarProducto.setText("Gestionar Medicamento");
        MENU_GestionarProducto.setPreferredSize(new java.awt.Dimension(255, 30));
        MENU_GestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarProductoActionPerformed(evt);
            }
        });
        menu_producto.add(MENU_GestionarProducto);

        jMenuBar1.add(menu_producto);

        menu_cliente.setForeground(new java.awt.Color(0, 0, 0));
        menu_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiencia.png"))); // NOI18N
        menu_cliente.setText("Cliente");
        menu_cliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_cliente.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente-satisfecho (1).png"))); // NOI18N
        MENU_nuevoCliente.setText("Nuevo Cliente");
        MENU_nuevoCliente.setPreferredSize(new java.awt.Dimension(235, 50));
        MENU_nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_nuevoClienteActionPerformed(evt);
            }
        });
        menu_cliente.add(MENU_nuevoCliente);

        MENU_GestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/la-satisfaccion-del-cliente.png"))); // NOI18N
        MENU_GestionarClientes.setText("Gestionar Clientes");
        MENU_GestionarClientes.setPreferredSize(new java.awt.Dimension(235, 50));
        MENU_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarClientesActionPerformed(evt);
            }
        });
        menu_cliente.add(MENU_GestionarClientes);

        jMenuBar1.add(menu_cliente);

        menu_facturar.setForeground(new java.awt.Color(0, 0, 0));
        menu_facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas.png"))); // NOI18N
        menu_facturar.setText("Venta");
        menu_facturar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_facturar.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas (1).png"))); // NOI18N
        MENU_nuevaVenta.setText("Nueva Venta");
        MENU_nuevaVenta.setPreferredSize(new java.awt.Dimension(225, 50));
        MENU_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_nuevaVentaActionPerformed(evt);
            }
        });
        menu_facturar.add(MENU_nuevaVenta);

        MENU_GestionarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/punto-de-venta.png"))); // NOI18N
        MENU_GestionarVentas.setText("Gestionar Ventas");
        MENU_GestionarVentas.setPreferredSize(new java.awt.Dimension(225, 50));
        MENU_GestionarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_GestionarVentasActionPerformed(evt);
            }
        });
        menu_facturar.add(MENU_GestionarVentas);

        jMenuBar1.add(menu_facturar);

        menu_categoria.setForeground(new java.awt.Color(0, 0, 0));
        menu_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queja.png"))); // NOI18N
        menu_categoria.setText("Reclamos");
        menu_categoria.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_categoria.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_NuevoCategoria.setText("Nueva Categoria");
        MENU_NuevoCategoria.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_NuevoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_NuevoCategoriaActionPerformed(evt);
            }
        });
        menu_categoria.add(MENU_NuevoCategoria);

        MENU_gestionarCategoria.setText("Gestionar Categoria");
        MENU_gestionarCategoria.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_gestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_gestionarCategoriaActionPerformed(evt);
            }
        });
        menu_categoria.add(MENU_gestionarCategoria);

        jMenuBar1.add(menu_categoria);

        menu_categoria1.setForeground(new java.awt.Color(0, 0, 0));
        menu_categoria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factura.png"))); // NOI18N
        menu_categoria1.setText("Bonificaciones");
        menu_categoria1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_categoria1.setPreferredSize(new java.awt.Dimension(170, 50));

        MENU_NuevoCategoria1.setText("Nueva Categoria");
        MENU_NuevoCategoria1.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_NuevoCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_NuevoCategoria1ActionPerformed(evt);
            }
        });
        menu_categoria1.add(MENU_NuevoCategoria1);

        MENU_gestionarCategoria1.setText("Gestionar Categoria");
        MENU_gestionarCategoria1.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_gestionarCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_gestionarCategoria1ActionPerformed(evt);
            }
        });
        menu_categoria1.add(MENU_gestionarCategoria1);

        jMenuBar1.add(menu_categoria1);

        menu_reportes.setForeground(new java.awt.Color(0, 0, 0));
        menu_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporte-de-negocios.png"))); // NOI18N
        menu_reportes.setText("Reportes");
        menu_reportes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menu_reportes.setPreferredSize(new java.awt.Dimension(150, 50));

        MENU_ReporteClientes.setText("Reportes Clientes");
        MENU_ReporteClientes.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_ReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ReporteClientesActionPerformed(evt);
            }
        });
        menu_reportes.add(MENU_ReporteClientes);

        Menu_reporteCategoria.setText("Reportes Categorias");
        Menu_reporteCategoria.setPreferredSize(new java.awt.Dimension(150, 50));
        Menu_reporteCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_reporteCategoriaActionPerformed(evt);
            }
        });
        menu_reportes.add(Menu_reporteCategoria);

        MENU_ReporteProductos.setText("Reportes Productos");
        MENU_ReporteProductos.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_ReporteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ReporteProductosActionPerformed(evt);
            }
        });
        menu_reportes.add(MENU_ReporteProductos);

        MENU_ReporteVentas.setText("Reportes Ventas");
        MENU_ReporteVentas.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_ReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ReporteVentasActionPerformed(evt);
            }
        });
        menu_reportes.add(MENU_ReporteVentas);

        jMenuBar1.add(menu_reportes);

        menu_cerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        menu_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        menu_cerrarSesion.setText("Cerrar Sesion");
        menu_cerrarSesion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        MENU_cerrarSesion.setText("Cerrar Sesion");
        MENU_cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 50));
        MENU_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_cerrarSesionActionPerformed(evt);
            }
        });
        menu_cerrarSesion.add(MENU_cerrarSesion);

        jMenuBar1.add(menu_cerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevoUsuarioActionPerformed
        // TODO add your handling code here:
        InterRegistrarVendedor vendedor = new InterRegistrarVendedor();
        jDesktopPane_menu.add(vendedor);
        vendedor.setVisible(true);

    }//GEN-LAST:event_menu_nuevoUsuarioActionPerformed

    private void MENU_nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_nuevoClienteActionPerformed
        // TODO add your handling code here:
        InterRegistrarCliente cliente = new InterRegistrarCliente();
        jDesktopPane_menu.add(cliente);
        cliente.setVisible(true);


    }//GEN-LAST:event_MENU_nuevoClienteActionPerformed

    private void MENU_ReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ReporteVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_ReporteVentasActionPerformed

    private void MENU_ReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ReporteClientesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MENU_ReporteClientesActionPerformed

    private void Menu_reporteCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_reporteCategoriaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_Menu_reporteCategoriaActionPerformed

    private void MENU_NuevoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_NuevoCategoriaActionPerformed
        // TODO add your handling code here:
        InternalJframeCategoria categoria = new InternalJframeCategoria();
        jDesktopPane_menu.add(categoria);
        categoria.setVisible(true);

    }//GEN-LAST:event_MENU_NuevoCategoriaActionPerformed

    private void MENU_gestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_gestionarCategoriaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_MENU_gestionarCategoriaActionPerformed

    private void nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_productoActionPerformed
        // TODO add your handling code here:
        InterMedicamento entrarProducto = new InterMedicamento();
        System.out.println("entrado a agregarProducto");

        jDesktopPane_menu.add(entrarProducto);
        entrarProducto.setVisible(true);


    }//GEN-LAST:event_nuevo_productoActionPerformed

    private void MENU_GestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarProductoActionPerformed

        InterGestionarMedicamento medicamento= new InterGestionarMedicamento();
        jDesktopPane_menu.add(medicamento);
        medicamento.setVisible(true);
        
    }//GEN-LAST:event_MENU_GestionarProductoActionPerformed

    private void gestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarUsuariosActionPerformed

        InterGestionarVendedor gestionarVendedor = new InterGestionarVendedor();
        jDesktopPane_menu.add(gestionarVendedor);
        gestionarVendedor.setVisible(true);
        
    }//GEN-LAST:event_gestionarUsuariosActionPerformed

    private void MENU_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarClientesActionPerformed
        // TODO add your handling code here:
        InterGestionarCliente clientes = new InterGestionarCliente();
        jDesktopPane_menu.add(clientes);
        clientes.setVisible(true);

    }//GEN-LAST:event_MENU_GestionarClientesActionPerformed

    private void MENU_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_nuevaVentaActionPerformed
        // TODO add your handling code here:
        InterRegistrarVenta venta = new InterRegistrarVenta();
        jDesktopPane_menu.add(venta);
        venta.setVisible(true);
    }//GEN-LAST:event_MENU_nuevaVentaActionPerformed

    private void MENU_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_cerrarSesionActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_MENU_cerrarSesionActionPerformed

    private void MENU_GestionarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_GestionarVentasActionPerformed

        InterGestionarVentas ventasGestion = new InterGestionarVentas();
        jDesktopPane_menu.add(ventasGestion);
        ventasGestion.setVisible(true);
        
    }//GEN-LAST:event_MENU_GestionarVentasActionPerformed

    private void MENU_ReporteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ReporteProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_ReporteProductosActionPerformed

    private void MENU_NuevoCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_NuevoCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_NuevoCategoria1ActionPerformed

    private void MENU_gestionarCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_gestionarCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MENU_gestionarCategoria1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MENU_GestionarClientes;
    private javax.swing.JMenuItem MENU_GestionarProducto;
    private javax.swing.JMenuItem MENU_GestionarVentas;
    private javax.swing.JMenuItem MENU_NuevoCategoria;
    private javax.swing.JMenuItem MENU_NuevoCategoria1;
    private javax.swing.JMenuItem MENU_ReporteClientes;
    private javax.swing.JMenuItem MENU_ReporteProductos;
    private javax.swing.JMenuItem MENU_ReporteVentas;
    private javax.swing.JMenuItem MENU_cerrarSesion;
    private javax.swing.JMenuItem MENU_gestionarCategoria;
    private javax.swing.JMenuItem MENU_gestionarCategoria1;
    private javax.swing.JMenuItem MENU_nuevaVenta;
    private javax.swing.JMenuItem MENU_nuevoCliente;
    private javax.swing.JMenuItem Menu_reporteCategoria;
    private javax.swing.JMenuItem gestionarUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_categoria;
    private javax.swing.JMenu menu_categoria1;
    private javax.swing.JMenu menu_cerrarSesion;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenu menu_facturar;
    private javax.swing.JMenuItem menu_nuevoUsuario;
    private javax.swing.JMenu menu_producto;
    private javax.swing.JMenu menu_reportes;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenuItem nuevo_producto;
    // End of variables declaration//GEN-END:variables
}
