/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.farmaciasaludproyecto.view.menu;

import com.mycompany.farmaciasaludproyecto.model.dao.DevolucionDAO;
import com.mycompany.farmaciasaludproyecto.model.dao.VentaDAO;
import com.mycompany.farmaciasaludproyecto.model.entity.Venta;
import static com.mycompany.farmaciasaludproyecto.view.menu.InterGestionarVentas.jTable_ventas;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesar
 */
public class InternalCrearDevolucion extends javax.swing.JInternalFrame {

    private DefaultTableModel dtm;
    private String[] cabeceras = {"ID Venta", "ID Cliente", "ID Vendedor", "ID Descuento", "Total", "Fecha Venta", "Vigente"};
    private VentaDAO ventaDao;
    private LinkedList<Venta> listaVentas;

    public void mostrarVentasEnJTable() {
        // Inicializar el modelo de la tabla con las cabeceras definidas
        dtm = new DefaultTableModel(null, cabeceras);

        // Llenar la lista de ventas
        ventaDao = new VentaDAO();
        listaVentas = ventaDao.obtenerVentas(); // Este método debería retornar la lista de ventas desde la base de datos

        // Recorrer la lista de ventas y agregar cada una al modelo de la tabla
        for (Venta venta : listaVentas) {
            // Aquí asumo que tienes un método en la clase Venta que convierte la venta en un arreglo de objetos
            dtm.addRow(venta.convertir());
        }

        // Establecer el modelo de la tabla
        jTable_productos1.setModel(dtm);

    }

    private void buscarVentaPorID(int idVenta) {
        // Limpiar la tabla antes de mostrar resultados
        dtm = new DefaultTableModel(null, cabeceras);
        jTable_productos1.setModel(dtm);

        // Buscar en la lista de ventas
        boolean encontrado = false; // Para manejar casos en los que no se encuentre nada
        for (Venta venta : listaVentas) {
            if (venta.getId_venta() == idVenta) { // Asumiendo que tienes un getter para `idVenta`
                // Agregar la venta encontrada a la tabla
                dtm.addRow(venta.convertir());
                encontrado = true;
                break;
            }
        }

        // Mostrar mensaje si no se encuentra ninguna venta
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna venta con el ID: " + idVenta,
                    "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public InternalCrearDevolucion() {
        initComponents();
        this.setSize(new Dimension(1150, 752));
        mostrarVentasEnJTable();
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                // Obtener los datos de la fila seleccionada
                int filaSeleccionada = jTable_productos1.getSelectedRow();

                if (filaSeleccionada != -1) {
                    int idVenta = (int) dtm.getValueAt(filaSeleccionada, 0); // Obtener el ID de venta
                    String motivo = jTextArea1.getText();  // Obtener el motivo de la devolución

                    if (!motivo.trim().isEmpty()) {
                        // Llamar al DAO para crear la devolución
                        DevolucionDAO devolucionDAO = new DevolucionDAO();
                        devolucionDAO.crearDevolucion(idVenta, motivo);

                        JOptionPane.showMessageDialog(null, "Devolución procesada con éxito.");

                        // Opcional: Limpiar los campos o actualizar la tabla
                        jTextArea1.setText("");  // Limpiar el campo de texto
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese un motivo para la devolución.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor, seleccione una venta de la tabla.");
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_busca_cliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_productos1 = new javax.swing.JTable();
        txt_cliente_buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motivacion.png"))); // NOI18N
        jLabel4.setText("Motivo");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 460, 130));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        jButton1.setText("Generar reporte");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 310, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devolucion-de-dinero (1).png"))); // NOI18N
        jButton2.setText("Procesar devolucion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 310, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 1040, 210));

        jButton_busca_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventas (1).png"))); // NOI18N
        jButton_busca_cliente.setText("Buscar venta");
        jButton_busca_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_busca_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 170, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_productos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_productos1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 1050, 340));

        txt_cliente_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cliente_buscar.setForeground(new java.awt.Color(0, 0, 0));
        txt_cliente_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cliente_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 200, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devolucion-de-dinero.png"))); // NOI18N
        jLabel2.setText("Devolucion");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel_wallpaper.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ucsm-farmacia-y-bioquimica (1).jpg"))); // NOI18N
        jLabel_wallpaper.setOpaque(true);
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_busca_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_clienteActionPerformed

        String textoID = txt_cliente_buscar.getText().trim();

        if (!textoID.isEmpty()) {
            try {
                // Intentar convertir el texto a un número
                int idVenta = Integer.parseInt(textoID);
                buscarVentaPorID(idVenta);
            } catch (NumberFormatException e) {
                // Mostrar un error si el ID no es un número válido
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de venta válido.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mostrar todas las ventas si no se ingresó un ID
            mostrarVentasEnJTable();
        }

    }//GEN-LAST:event_jButton_busca_clienteActionPerformed

    private void jTable_productos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productos1MouseClicked

        int filaSeleccionada = jTable_productos1.getSelectedRow();

        // Verificar que se haya seleccionado una fila
        if (filaSeleccionada != -1) {
            // Obtener los valores de la fila seleccionada
            int idVenta = (int) dtm.getValueAt(filaSeleccionada, 0); // ID Venta
            int idCliente = (int) dtm.getValueAt(filaSeleccionada, 1); // ID Cliente
            int idVendedor = (int) dtm.getValueAt(filaSeleccionada, 2); // ID Vendedor
            int idDescuento = (int) dtm.getValueAt(filaSeleccionada, 3); // ID Descuento

            // Convertir BigDecimal a Double para la columna Total
            BigDecimal totalBigDecimal = (BigDecimal) dtm.getValueAt(filaSeleccionada, 4);
            double total = totalBigDecimal.doubleValue();

            // Convertir a Date si es necesario (asegúrate de que sea compatible)
            Date fechaVenta = (Date) dtm.getValueAt(filaSeleccionada, 5);

        }


    }//GEN-LAST:event_jTable_productos1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mostrarVentasEnJTable();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_busca_cliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable_productos1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_cliente_buscar;
    // End of variables declaration//GEN-END:variables
}
